### ISSUE TITLE
Orientation Lock Option

### ISSUE THREAD

**Issue by rickvanprim** [wtsnz/obs-ios-camera-source#15]
It would be nice to be able to lock the camera in portrait or landscape mode, so it doesn't abruptly changed during a stream.

**Comment by wtsnz** [comment]
He @rickvanprim!

Thanks for the suggestion! I didn't think that people would move the device around whilst filming, and thought that most people would use a tripod/mount. 

If this would be helpful then I'll certainly take a look at implementing this when I update the app to use the new iOS 12 SDK.

**Comment by rickvanprim** [comment]
Our use case is using the iPhone as a steady cam to supplement a fixed camera on a tripod.  It's not a huge deal as long as we're consistent about holding it sideways in landscape mode.

I could see two approaches for this, either an orientation setting for Auto, Portrait, Landscape, or just on the main screen a orientation lock toggle button.  Or both?

Thanks for the quick response :)

**Comment by wtsnz** [comment]
Is there a reason that the iPhone's global rotation lock doesn't achieve what you're after?

**Comment by benrossow** [comment]
I have tried two different iPhones mounted on a tripod. The orientation changes from landscape to portrait after a few minutes. They are sitting stationary and don't receive any movement at all during recording. Is there a way to prevent this?

**Comment by wookayin** [comment]
If global rotation lock is set, obs camera will always send frames in the **portrait** mode --- I'd rather want to lock in the landscape mode. Can we have this option added?
