### ISSUE TITLE
OBS crashes on exit

### ISSUE THREAD

**Issue by zerodistraction** [wtsnz/obs-ios-camera-source#16]
Problem: I have configured two iPhones in OBS, however, I’ve noticed OBS is now extremely unstable and crashes on exit. Streaming is reliable and the app works reliable while I’m in it, but it consistently crashes on exit. If I try to even remove a iOS camera source, OBS crashes.

When I looked at the crash log, I see it’s saying right after it loads iOS Camera, it’s complaining that the NDI library is old and requires 5.11.

"20:31:16.130:   Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later,”

Then a TON of these lines repeated:

:31:29.428: [obs-ios-camera-plugin] Error decoding video
20:31:29.438: [obs-ios-camera-plugin] Error decoding video
20:31:29.451: [obs-ios-camera-plugin] Error decoding video
20:31:29.473: [obs-ios-camera-plugin] Error decoding video
20:31:29.484: [obs-ios-camera-plugin] Error decoding video
20:31:29.507: [obs-ios-camera-plugin] Error decoding video
20:31:29.520: [obs-ios-camera-plugin] Error decoding video
20:31:29.543: [obs-ios-camera-plugin] Error decoding video
20:31:29.554: [obs-ios-camera-plugin] Error decoding video
20:31:29.567: [obs-ios-camera-plugin] Error decoding video
20:31:29.577: [obs-ios-camera-plugin] Error decoding video
20:31:29.599: [obs-ios-camera-plugin] Error decoding video
20:31:29.599: [obs-ios-camera-plugin] Error decoding video
20:31:29.601: [obs-ios-camera-plugin] Error decoding video
20:31:29.802: Last log entry repeated for 7 more lines
20:31:29.802: adding 21 milliseconds of audio buffering, total audio buffering is now 149 milliseconds
20:31:29.846: [obs-ios-camera-plugin] Error decoding video

I have configured two iPhones in OBS, however, I’ve noticed OBS is now extremely unstable and crashes on exit. Streaming is reliable and the app works reliable while I’m in it, but it consistently crashes on exit.

When I looked at the crash log, I see it’s saying right after it loads iOS Camera, it’s complaining that the NDI library is old and requires 5.11.

"20:31:16.130:   Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later,”

Then a TON of these lines repeated:

:31:29.428: [obs-ios-camera-plugin] Error decoding video
20:31:29.438: [obs-ios-camera-plugin] Error decoding video
20:31:29.451: [obs-ios-camera-plugin] Error decoding video
20:31:29.473: [obs-ios-camera-plugin] Error decoding video
20:31:29.484: [obs-ios-camera-plugin] Error decoding video
20:31:29.507: [obs-ios-camera-plugin] Error decoding video
20:31:29.520: [obs-ios-camera-plugin] Error decoding video
20:31:29.543: [obs-ios-camera-plugin] Error decoding video
20:31:29.554: [obs-ios-camera-plugin] Error decoding video
20:31:29.567: [obs-ios-camera-plugin] Error decoding video
20:31:29.577: [obs-ios-camera-plugin] Error decoding video
20:31:29.599: [obs-ios-camera-plugin] Error decoding video
20:31:29.599: [obs-ios-camera-plugin] Error decoding video
20:31:29.601: [obs-ios-camera-plugin] Error decoding video
20:31:29.802: Last log entry repeated for 7 more lines
20:31:29.802: adding 21 milliseconds of audio buffering, total audio buffering is now 149 milliseconds
20:31:29.846: [obs-ios-camera-plugin] Error decoding video

I have both iPhones connected over Lightning USB.

Additionally, sometimes one of the iPhones won’t initialize right away and I have to wait a minute or unplug one and plug it back in for the video to come back.

I’m using OBS 22.0.3 (latest version of this this writing) on macOS 10.14.

Camera 1: iPhone 6 Plus running iOS 12.1.

Camera 2: iPhone X running iOS 12.1.

Computer: 2012 2.4Ghz 12-core Mac Pro. 64GB of RAM. AMD RX 580 GPU.

I removed the iOS Camera plugin and now OBS no longer crashes, so it definitely is related to the plugin.

**Comment by wtsnz** [comment]
Fixed with the latest version 👍  - [v2.5.0](https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.5.0)

Thanks again @zerodistraction for your help with this issue 😃
