### ISSUE TITLE
Huge Delay over time

### ISSUE THREAD

**Issue by CSchelll** [wtsnz/obs-ios-camera-source#19]
I know there was already a thread on this, but i didnt find a clear answer to it so i will ask again. When i try to use my phone as the camera it works fine for the first couple minutes and then it gets really delayed and laggy. Any fix?

**Comment by wtsnz** [comment]
This is likely a side effect of the machine that is doing the streaming is doing too much work simultaneously.

Closing this as I have no more to add.
