### ISSUE TITLE
Obs won't Load the Plugin on windows

### ISSUE THREAD

**Issue by InkxtheSquid** [wtsnz/obs-ios-camera-source#28]
I have no clue why but for some reason the plugin won't load on obs-studio 24.0.1 on windows. however I see videos of the plugin working in older versions, I reeeeaally want to use this plugin badly without any flaws, and I don't want to downgrade to an older version of obs-studio to fix this, please fix this problem I am having, on top of that I found this in one of my log files

```
22:57:56.298: LoadLibrary failed for '../../obs-plugins/64bit/obs-ios-camera-source.dll': The specified module could not be found.
22:57:56.298:  (126)
22:57:56.298: Module '../../obs-plugins/64bit/obs-ios-camera-source.dll' not loaded
```

**Comment by wtsnz** [comment]
Thanks, I'm looking into this, it's working here on my Windows computer and I've not been able to reproduce the issue.

I'll in the process of re-installing the latest version of Windows 10 and attempting to reproduce.

**Comment by wtsnz** [comment]
@InkxtheSquid this is fixed with the latest version! Download the updated plugin below

https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.5.1

**Comment by InkxtheSquid** [comment]
Thank you So much! it shows on the latest version now!
