### ISSUE TITLE
Twitch Chat

### ISSUE THREAD

**Issue by EgidioBezerra** [wtsnz/obs-ios-camera-source#38]
It could be nice if u implement a twitch chat feature, just like when u press to turn the screen off, we could press to show our stream chat.

**Comment by wtsnz** [comment]
Thanks for the suggestion. I feel this is out of scope for this project, so I'm going to have to say that I won't be able to add this into the iOS app.

There are a few ways to add twitch chat into OBS Studio via other plugins - like this https://www.youtube.com/watch?v=BCkDMIppyL0&ab_channel=GamingCareers

Best
