### ISSUE TITLE
controlling zoom from within obs

### ISSUE THREAD

**Issue by dunn** [wtsnz/obs-ios-camera-source#42]
Is it possible for the OBS plugin to adjust the zoom level of the camera (or on an iPhone Pro, the lens used)?  It would be very useful to have, for example, two source instances at different zoom levels that could be switched between.

Thanks!

**Comment by eric** [comment]
I would really use this as well.

**Comment by wtsnz** [comment]
While it's not exactly from within OBS Studio, we've added the ability to control the app using websockets. The app now can enable a small webserver that hosts a web page that let's you control most aspects of the camera.

Check out more details in the app's Output settings 👍
