### ISSUE TITLE
Delay image

### ISSUE THREAD

**Issue by josep112** [wtsnz/obs-ios-camera-source#44]
i'm using macosx i5 16g ram with usb cable and iphone.
after a minute or the video is delayed from 3 seconds after 2 seconds to 8 seconds and therefore ahead, which can be a CPU that is around 20%

**Comment by wtsnz** [comment]
Hey @josep112 have you updated to the latest version of the plugin? - v2.6.0? https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.6.0

Enabling the Hardware Decode option in the iOS Camera Source Properties will provide a substantial speed bump too!
