### ISSUE TITLE
Crash when launching OBS with obs-ios-camera-source v2.6.1 (macOS 10.15.3)

### ISSUE THREAD

**Issue by venn-xx** [wtsnz/obs-ios-camera-source#46]
I get a crash when attemping to launch OBS for a second time when v2.6.1 of the ios-camera-source is installed.

Hardware:
MacBook Pro (16-inch 2019)
MacOS Catalina 10.15.3

Reproduction steps:
1. Install obs-ios-camera-source v2.6.1
2. Launch OBS (24.0.8)
3. Add and connect an an iOS Camera source following the [getting started guide](https://obs.camera/docs/getting-started/ios-camera-plugin-usb/) (I used an iPhone SE)
4. Quit OBS
5. Launch OBS 

Actual result:
OBS logo bounces in the dock for a long time then crashes without opening.

Expected result:
OBS launches

Workaround:
- If I delete v2.6.1 and install v2.6.1 again, OBS launches correctly once, then crashes on every subsequent launch.
- Downgrading to v2.6.0 seems to fix the crashes.

macOS Crash dump:
https://pastebin.com/MgxD2Myw

**Comment by waleeg** [comment]
Hi @venn-xx 

That's weird, thanks for the report. 
Could you send the OBS logs? One of them will be linked to the crash.

Thanks.

**Comment by venn-xx** [comment]
Hi @waleeg, unfortunately I don't think any OBS logs were created, the oldest log file in my logs folder still indicates "Loading iOS Camera Plugin (version 2.6.0)" so this would have been after I downgraded from 2.6.1 to 2.6.0.

I'll attach the two log files created on 1 June 2020 regardless.

Thanks 

[2020-06-01 23-22-54.txt](https://github.com/wtsnz/obs-ios-camera-source/files/4733287/2020-06-01.23-22-54.txt)

[2020-06-01 17-24-11.txt](https://github.com/wtsnz/obs-ios-camera-source/files/4733286/2020-06-01.17-24-11.txt)

**Comment by wtsnz** [comment]
Hey @venn-xx,

Just wanted to follow up; are you still experiencing this issue on every subsequent launch of OBS Studio?

I've looked at the crash dump and it's not really helpful (to my eyes!) - it's saying that the main thread crashed while loading the `vlc-video.so` plugin. However, this is likely not the cause if you can prevent the crash by downgrading the ios-camera-source plugin.

If you do continue to see this issue, could you see how the pre-release version (v2.7.0 - https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.7.0) goes for you?

Best
