### ISSUE TITLE
Massive video delay over time

### ISSUE THREAD

**Issue by aqQnm0** [wtsnz/obs-ios-camera-source#5]
I have an issue with the video coming from the iPhone. It's fine for the first few minutes, but it gets more and more delayed over time. After only ~15 min the video is over 10 seconds delayed, even on 720p. It's a bit choppy as well.

iPhone 7 Plus
OBS 21.1 on Windows 8.1 (both up-to-date)
Core i7 (8-Core/16-Thread), GTX 1070, 16GB RAM

**Comment by wtsnz** [comment]
Hey @aqQnm0,

Sorry I took so long to get back to you. Interesting, it sounds like the decoding on the computer isn't able to keep up over long durations.

A few questions:
- Does the scene in OBS Studio have a lot of sources? 
- What's the CPU indicator at the bottom say during recording/streaming/ready?
- Do you get any warnings from the iOS Camera plugin printed to the [logfile](https://watchbeam.zendesk.com/hc/en-us/articles/217375746-How-to-get-your-log-files)? 

Thanks!

**Comment by EveningStarNM** [comment]
I've had the same problem. On an old 3GHz Core 2 Extreme Quad with and AMD Radeo HD 6670, I had no significant problems with the old version, but the new version gets farther and farther behind over time. After a couple of minutes, the OBS video would be 15 seconds behind real life, and getting worse. However, on my Dell Precision M7720 (Core i7-7700 HQ with Intel HD Graphics 630 and nVidia Quadro P3000), the problem has disappeared.

**Comment by CSchelll** [comment]
i think that the 2.3.2 update fixes it but i am on windows :(

**Comment by wtsnz** [comment]
This is likely a side effect of the machine that is doing the streaming is doing too much work simultaneously.

Closing this as I have no more to add.

**Comment by thSoft** [comment]
Also reproducible during streaming with
* OBS Camera 3.1
* OBS 25.0.6
* MacBook Pro mid-2015 with macOS 10.15.4
* iPhone 8 with iOS 13.3.1

**Comment by Thomas-p2-Elliot** [comment]
This issue is still happening. I do not have the log. CPU & GPU Usage were below 30% but after ~20 minutes a delay became noticeable, and slowly grew worse and worse until the stream crashed.
