### ISSUE TITLE
iOS doesn't 'save' previous settings if crashing

### ISSUE THREAD

**Issue by thesammykins** [wtsnz/obs-ios-camera-source#55]
Using 3.1.1-79, when the app crashes if I have set up custom settings (ISO, WB, Zoom, etc) they are not saved in any form, so when you load it back up you either have to have noted your calibration or start from scratch.

It would be great if by default it saved the last used settings when starting up, or give options for profiles e.g. Day profile and Night profile in this manner as I find myself just defaulting to using Filmic Pro's HDMI output option as it allows saving profiles like this, however at the loss of the visual quality I get over USB from this app.

**Comment by wtsnz** [comment]
Thanks for the suggestion; this makes sense!

I've added it to the roadmap, so we'll take a look at how best to implement.
