### ISSUE TITLE
macOS Lockup/crash when using OBS Camera with Virtual Webcam

### ISSUE THREAD

**Issue by thomaslfessler** [wtsnz/obs-ios-camera-source#57]
**Hardware / OS Info** 
Booting with Open Core 0.5.8 and macOS 10.15.5
Booting with Open Core 0.6.3 and macOS 10.15.7
iPhone 7+ or iPhone 12 Pro Max
AMD Ryzen 3900x, AMD 5700XT, 128GB ram etc. 
Plugged into USB 2.0, 3,0 or 3.2 Gen 2x2 ports

**Software Info** 
OBS 26.02. (I just upgraded to 26.1 - afraid to try again)
Virtual Webcam for Mac 1.3.1
When using OBS.Camera over USB as a source,  macOS randomly hard locks and needs a forced reboot.
For a point of reference:  This is the 1st time I have ever seen a hard-crash on macOS.    

**Other info* 
EpocCam does not crash.
Capturing the iOS device screen, using an app like FullScreen Camera does not crash.
Attempting a similar setup on Windows last week, I saw a similar hard-lock crash behavior with OBS.camera.
I'm sure there are plenty of crash reports I can pull from the SSD to submit.

**Thoughts**
Have you considered this pull request for:  Add thread safety to VideoToolbox decoder
Something is throwing a _low-level system exception_ that prevents the OS from surviving.

**Additional Info**
Switching to a "FREE" app like FullScreen Camera and using a capture device that grabs the iOS screen keeps macOS from hard locking ./ crashing.    There is definitely something up with OBS.camera when streaming though a virtual webcam.   Considering the **cost of OBS.camera on the AppStore**, these crashes really need to be addressed.

**Comment by wtsnz** [comment]
Hey @thomaslfessler, 

Thanks for the issue report. I'm not sure how the plugin could be causing macOS itself to lock up. Crashes related to the plugin tend to be limited to the host app (OBS Studio in this case).

Today, I've merged in the PR you mentioned that improves the thread safety of the macOS hardware decoder. It's included along with a couple of other improvements regarding device connectivity. 

I've created a pre-release of v2.7.0 that I like you to try and see if you can replicate the issue. https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.7.0

Let me know if you have any more information, and how you get on. Cheers!
