### ISSUE TITLE
Feature request: OBS Camera Remote

### ISSUE THREAD

**Issue by jfrux** [wtsnz/obs-ios-camera-source#67]
I know, as a developer... nothing is ever good enough for everyone... but I just want to say that this app is phenomenal and you've done a great job Will!

Stashing this here, but I like to use the forward facing camera for OBS as it is generally magnitudes better than the selfie camera but cannot properly expose the shot to my self without reversing the device to touch the screen...

Any tips on how one might be able to do some of this remotely?
Or any plans on building a simple remote tool that can tweak the settings.

**Comment by wtsnz** [comment]
This is now out!

We've added the ability to remotely control the device using websockets. 

Check out more details in the app's Output settings 👍
