### ISSUE TITLE
Runs on Apple Silicon / M1 / ARM machines

### ISSUE THREAD

**Issue by adrianboisclair** [wtsnz/obs-ios-camera-source#72]
Any thoughts on this?

**Comment by makanys** [comment]
Hello, I try to compile plugin, but not work. "Warning: No available formula or cask with the name "./ci/macos/qt.rb" Can you help to me? Thank you!

**Comment by wtsnz** [comment]
I've only just got my hands on the M1 mac, and it's on my list to investigate in the next week or two! If you find out more, please share :) 

For now, the pre-compiled plugin works great on the M1 machines.

**Comment by makanys** [comment]
Yes it's work, but with compiled OBS not work :( with intel OBS no problem, but... :)

**Comment by wtsnz** [comment]
I'm not sure I follow.

This plugin doesn't work with a version of OBS Studio you've compiled yourself?

**Comment by makanys** [comment]
Yes. :( this is the problem.

**Comment by wookayin** [comment]
OBS 28.0 will start supporting arm64, and actually the latest nightly build has arm64 version. The ios-camera source binary is only in x86_64 architecture, so the plugin cannot be loaded when OBS is running as arm64.

Please see the error message:
```
error: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Now that OBS has started supporting arm64 officially, this plugin should be fixed to produce universal (arm64/x86_64) binary sooner than later.

**Comment by wes-nz** [comment]
Thanks for the update @wookayin we are on it.
