### ISSUE TITLE
Installer not working?

### ISSUE THREAD

**Issue by seffyroff** [wtsnz/obs-ios-camera-source#8]
Hey there, with the latest Windows version of the installer, the plugin doesn't appear in my OBS plugins directory.  My OBS Studio isn't installed in the default directory, and is in fact installed using [Scoop](https://github.com/lukesampson/scoop-extras/blob/master/obs-studio.json) so it's possible that env vars your installer is looking for aren't there.  Is it possible to provide a manual install so I can just drop the .dll in the right place?

**Comment by wtsnz** [comment]
Hey @seffyroff, sorry for the delay in getting back to you.

I've extracted the files from the installer for you and attached them here. 
[installer-files.zip](https://github.com/wtsnz/obs-ios-camera-source/files/2128775/installer-files.zip)

<img width="750" alt="screen shot 2018-06-22 at 11 46 53 am" src="https://user-images.githubusercontent.com/665916/41793772-fe850c4e-7611-11e8-91ef-67f4507cc1c9.png">

I couldn't quite figure out where Scoop installs OBS Studio to, but was under the impression that OBS Studio looks inside it's installed directory (from here https://obsproject.com/forum/resources/obs-and-obs-studio-install-plugins-windows.421/)

Hopefully this helps somewhat?

**Comment by seffyroff** [comment]
That worked, thanks!

Scoop installed apps are subdirectories of it's own install, which defaults to the user's home dir (they advise keeping it inside a dir structure owned by the current user so it can install stuff without admin perms).  I think the regular OBS installer sets an Env Var to the installed directory, which it seems the Scoop installer isn't doing.  I'll verify this and file a bug with them.
