### ISSUE TITLE
2.9.1 doesnt work on Windows

### ISSUE THREAD

**Issue by dungi** [wtsnz/obs-ios-camera-source#82]
![grafik](https://user-images.githubusercontent.com/3323565/171698616-e51b1ffe-7f3e-4885-af55-be0dcfbaca01.png)

After installing 2.9.1 (64bit Version) OBS doesn't show the plug-in correctly.

**Comment by wtsnz** [comment]
Thanks for testing - to clarify, which version of OBS Studio are you using @dungi?

**Comment by dungi** [comment]
27.2.3 - should be the latest

**Comment by wtsnz** [comment]
Interesting, thanks for that @dungi! One last thing - was there anything of interest in the OBS Studio Log File explaining why it wouldn't load?

**Comment by dungi** [comment]
Only found this:

21:58:02.724: Loading iOS Camera Plugin (version 2.9.1)
21:58:02.724: obs_register_source: Tried to register obs_source_info with size 400 which is more than libobs currently supports (392)

21:58:03.576: Source ID 'ios-camera-source' not found
21:58:03.576: Failed to create source 'iOS Camera'!

**Comment by dungi** [comment]
All right :) Cause I have the bug with the "scene switch" and wanted to try out if this worked for me. I will go back to the older version. And try the new one out, if it's fixed.

**Comment by Espionage724** [comment]
> 27.2.3 - should be the latest

I don't believe it'll change anything, but 27.2.4 is the latest currently https://github.com/obsproject/obs-studio/releases/tag/27.2.4

**Comment by dungi** [comment]
> > 27.2.3 - should be the latest
> 
> I don't believe it'll change anything, but 27.2.4 is the latest currently https://github.com/obsproject/obs-studio/releases/tag/27.2.4

You're right. I just updated... but still, doesn't work :)

**Comment by Keysureshm** [comment]
28.0 beta 1 installed working fine. but 2.9.1 obs iOS camera source not working.

**Comment by Keysureshm** [comment]
<img width="897" alt="Screenshot 2022-08-04 at 4 00 04 PM" src="https://user-images.githubusercontent.com/109102007/182826077-f10f1c79-8514-41b8-ba71-a4ceefbc14fe.png">

**Comment by Keysureshm** [comment]
<img width="903" alt="Screenshot 2022-08-04 at 4 01 36 PM" src="https://user-images.githubusercontent.com/109102007/182826333-7ede9b6e-66a9-443f-97ea-4de0b4a598c3.png">

**Comment by RoneyThomas** [comment]
I also have the same issue as the above comment but M1 Mac. I am on OBS 28.0.1 beta arm64 Mac and using the 2.9.1 Mac arm plugin.

**Comment by Keysureshm** [comment]
I found there is a option, under Video capture device,u can select your apple iPhone device  to use sa a camera.it’s working good .

**Comment by RoneyThomas** [comment]
@Keysureshm I see the option but isn't using the obs-ios-camera plugin, instead you are using the native OBS feature and it can only mirror your iPhone and there is no Audio.

**Comment by Keysureshm** [comment]
Yes Your Right.we need to wait to update the plug-in.

**Comment by Keysureshm** [comment]
I am Also using MacBook Pro M1 and IMac M1.

**Comment by RoneyThomas** [comment]
On my mac fully removed the plugin by deleting it from plugin directory. Downloaded the arm64 2.9.1 version. Here is the relevant log related to it.
```
23:06:32.652: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source, 0x0101): Library not loaded: '@rpath/libavcodec.58.134.100.dylib'
23:06:32.652:   Referenced from: '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source'
23:06:32.652:   Reason: tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/libavcodec.58.134.100.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libavcodec.58.134.100.dylib' (no such file), '/usr/lib/libavcodec.58.134.100.dylib' (no such file)
23:06:32.652: 
23:06:32.652: Module '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source' not loaded
23:06:32.652: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source, 0x0101): Library not loaded: '@rpath/libavcodec.58.134.100.dylib'
23:06:32.652:   Referenced from: '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source'
23:06:32.652:   Reason: tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/libavcodec.58.134.100.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libavcodec.58.134.100.dylib' (no such file), '/usr/lib/libavcodec.58.134.100.dylib' (no such file)
23:06:32.652: 
23:06:32.652: Module '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source.plugin/Contents/MacOS/obs-ios-camera-source' not loaded
23:06:32.652: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
23:06:32.652: 
23:06:32.652: Module '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' not loaded
23:06:32.652: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
23:06:32.652: 
23:06:32.652: Module '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' not loaded
23:06:32.652: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```
OBS 28 beta 1 only has libavcodec.59.18.100.dylib and the plugin is referencing libavcodec.58.134.100.dylib.
I think version bump should fix it.

**Comment by Keysureshm** [comment]
Yes 👍🏻.

**Comment by Keysureshm** [comment]
Thank u.

**Comment by wtsnz** [comment]
For people on the OBS Studio 28.0 Beta, I've cut a new build that works - https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.9.2

It's not perfect on Windows right now, but I'm looking into it.

**Comment by Keysureshm** [comment]
Thank u So Much Its Working Fine Now. Web Socket Also Not Working With Touch Portal On 28.0 Beta 2. I Hope It Will Also Work Fine With Beta 3 Atleast
<img width="914" alt="Screenshot 2022-08-18 at 9 47 44 AM" src="https://user-images.githubusercontent.com/109102007/185292775-664405c2-eb38-43c2-a1aa-7e7204ee02d7.png">
