### ISSUE TITLE
Obs - Camera Source NOT WORKING with OBS 29.0.0

### ISSUE THREAD

**Issue by Keysureshm** [wtsnz/obs-ios-camera-source#89]
obs - iOS camera source,not working with OBS 29.0.Today I got update notification from obs.after update to 29.0.0,ios camera source not working anymore.i tried with beta 3 29.0 also.After I downgrade to 28.1.2,Obs - iOS camera source is working fine,please fix this issue ,Thank u.

**Comment by wtsnz** [comment]
Fixing this now, tracking in #90
