### ISSUE TITLE
iOS Camera Plugin gone with OBS 29 on Mac

### ISSUE THREAD

**Issue by jph112233** [wtsnz/obs-ios-camera-source#90]
After upgrading to OBS 29 the plug-in is no longer available in OBS.  I tried to re-run the installer for 2.9.3 (with OBS closed) but it did not add it.  When I double-click a iOS Camera Source that was added to a scene prior to the upgrade to OBS 29, "No Properties Available". See attached.

Thanks for such building a sweet plugin!!

![Screenshot 2023-01-09 at 10 05 38 AM](https://user-images.githubusercontent.com/16183007/211353351-e63865fb-944f-4213-a96b-1a2c9c90827b.png)

**Comment by wtsnz** [comment]
I'm looking into it today. Hopefully will get a build out that fixes the compatibility with OBS 29 shortly :)

**Comment by wtsnz** [comment]
Could you please try from the pre-release I've just created. It works here but it'll be good to get confirmation from you too! https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v2.9.4

Thanks :)

**Comment by chris2cant** [comment]
Hi, it's not working for me. The `IOS Camera` option is not available
![image](https://user-images.githubusercontent.com/11084022/211507228-67fa9fc4-d091-4521-a2d1-be2b26fd13bc.png)

**Comment by Massimix** [comment]
I confirm, downloaded v2.9.4, installed and it works! Thanks, nice work

**Comment by wtsnz** [comment]
Thanks for checking everyone! Am updating the website to add a download link to this release 👍
