### ISSUE TITLE
OBS Studio 30.0

### ISSUE THREAD

**Issue by slavakurilyak** [wtsnz/obs-ios-camera-source#96]
It would be great to get a bump to the latest [OBS Studio 30.0](https://github.com/obsproject/obs-studio/releases/tag/30.0.0) version

**Comment by cjohn001** [comment]
I am also considering to buy the app. However, with a look to the last commit it seems like the project is dead?

**Comment by wtsnz** [comment]
As is, everything works as expected for OBS 30.0 😄
