### ISSUE TITLE
I was about to purchase, and I noticed it's not configured for OBS 30?

### ISSUE THREAD

**Issue by myrddin64** [wtsnz/obs-ios-camera-source#97]
I have seen lots of plugins stop working due to late versions of OVS. I am currently on 30 and have had to remove some already (free ones) I can't risk a purchase unless I know this one is supported on the today release as well as the future releases to come.

**Comment by wtsnz** [comment]
Hey @myrddin64 - the latest version of the plugin is compatible with OBS Studio 30.0+. I've continue to use it daily :)
